repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: >
              (?x)^(
              data/.*|
              docs/.*|
              renv/.*|
              .*\.feather|
              .*\.rds|
              .*\.Rds|
              .*\.RData
              )$
    -   id: end-of-file-fixer
        exclude: >
              (?x)^(
              data/.*|
              docs/.*|
              renv/.*|
              .*\.feather|
              .*\.rds|
              .*\.Rds|
              .*\.RData
              )$
    -   id: check-yaml
        exclude: >
              (?x)^(
              data/.*|
              docs/.*|
              renv/.*|
              )$
    -   id: check-added-large-files
        args: ["--maxkb=80000"]
    -   id: no-commit-to-branch
        args: [--branch, master, --branch, main]
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
    -   id: no-browser-statement
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
        exclude: >
              (?x)^(
              data/.*|
              docs/.*|
              renv/.*
              )$
    -   id: parsable-R
        exclude: >
              (?x)^(
              data/.*|
              docs/.*|
              renv/.*
              )$
    -   id: roxygenize
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.26.0
    hooks:
    -   id: markdownlint
        args: [--fix]
        exclude: "^LICENSE.md$"
